<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="main" Id="{a5da58b8-5a34-42e4-a5de-1b0ec0c09d5b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM main
VAR
	init: BOOL := FALSE;
	shelf: Shelf(10, 10);
	p: IPart;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="main">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>